import requests
from lxml import html
import time
import praw

def sort(inputList):

	isSorted=False;	
	while(isSorted==False):
		isSorted=True
		for i in range(len(inputList)-1):
			if(inputList[i].score > inputList[i+1].score):
				inputList[i], inputList[i+1] = inputList[i+1], inputList[i]
				isSorted=False
	return inputList

def getTrumpScore(allTrump):
	score = 0
	reddit=praw.Reddit(client_id='6lRl_cUXUxWshA',client_secret="cZIP9CTLIE9H09718IE1fCF1DCM", user_agent='damageReport Bot 1',username="TrumpReportBot",password="TrumpReportBotPassword")
	
	subreddit = reddit.subreddit("all")
	for submission in subreddit.hot(limit=200):
		score+=submission.score
	score = 100*(allTrump/score)
	return score


def makePost(inputList):
	reddit=praw.Reddit(client_id='6lRl_cUXUxWshA',client_secret="cZIP9CTLIE9H09718IE1fCF1DCM", user_agent='damageReport Bot 1',username="TrumpReportBot",password="TrumpReportBotPassword")
	
	
	
	
	dateAndTime = time.strftime("%A")+" "+time.strftime("%B")+" "+time.strftime("%d")+" at "+time.strftime("%I")+":"+time.strftime("%M") 
	print(dateAndTime)
	
	title = "Trump Report as of "+dateAndTime
	
	print(title)
	
	#sort the input list of submissions before making into the body of the post
	
	inputlist = sort(inputList).reverse()
	
	body = []
	trumpScore=0
	for submission in inputList:
		trumpScore+=submission.score
		temp = "[ #"+str(inputList.index(submission)+1)+" | +"+str(submission.score)+" ]\n\n"
		temp = temp + "["+submission.title+"]("+submission.url+") \n\n  "
		body.append(temp)
		
	
	info = """
	Info: This is generated by a bot based on the top 200 posts in 'hot' of various subreddits
	
	"""
	body.append(info)
	
	trumpScore = getTrumpScore(trumpScore)
	start ="Trump Percent of the day: "+str(round(trumpScore,2))+"%\n\n"
	
	body.insert(0,start)
	
	
	body="\n\n\n".join(body)
	
	
	print(body)
	
	
	
	
	reddit.subreddit("TrumpReport").submit(title,body)
	


def removeDups(inputList):
	tempSet =set()
	outputList = []
	for item in inputList:
		tempSet.add(item)
	for item in tempSet:
		outputList.append(item)
	return outputList

def getList():

	trumpReddits = ["all","news","worldnews","science","politics"]
	trumpSynonyms = ["trump","president"]
	trumpList = []

	reddit=praw.Reddit(client_id='6lRl_cUXUxWshA',client_secret="cZIP9CTLIE9H09718IE1fCF1DCM", user_agent='damageReport Bot 1',username="TrumpReportBot",password="TrumpReportBotPassword")

	for item in trumpReddits:
		subreddit = reddit.subreddit(item)
		for submission in subreddit.hot(limit=200):
			temptTitle = submission.title.lower()
			for synonym in trumpSynonyms:
				if(synonym in temptTitle):
					trumpList.append(submission)	
	return trumpList	


#program starts here


startTime = time.time()

mainList = getList()
mainList = removeDups(mainList)

makePost(mainList)

	
print("\n",time.time()-startTime,"seconds to run")

